/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PayRouteImport } from './routes/pay'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DecideRouteImport } from './routes/decide'
import { Route as CheatSheetRouteImport } from './routes/cheat-sheet'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as BonusesRouteImport } from './routes/bonuses'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPlaidWebhookRouteImport } from './routes/api/public/plaid/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideRoute = DecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatSheetRoute = CheatSheetRouteImport.update({
  id: '/cheat-sheet',
  path: '/cheat-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusesRoute = BonusesRouteImport.update({
  id: '/bonuses',
  path: '/bonuses',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlaidWebhookRoute = ApiPublicPlaidWebhookRouteImport.update({
  id: '/api/public/plaid/webhook',
  path: '/api/public/plaid/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/bonuses': typeof BonusesRoute
  '/cards': typeof CardsRoute
  '/cheat-sheet': typeof CheatSheetRoute
  '/decide': typeof DecideRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/pay': typeof PayRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/purchases': typeof PurchasesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/public/plaid/webhook': typeof ApiPublicPlaidWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/bonuses': typeof BonusesRoute
  '/cards': typeof CardsRoute
  '/cheat-sheet': typeof CheatSheetRoute
  '/decide': typeof DecideRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/pay': typeof PayRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/purchases': typeof PurchasesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/public/plaid/webhook': typeof ApiPublicPlaidWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/bonuses': typeof BonusesRoute
  '/cards': typeof CardsRoute
  '/cheat-sheet': typeof CheatSheetRoute
  '/decide': typeof DecideRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/pay': typeof PayRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/purchases': typeof PurchasesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/public/plaid/webhook': typeof ApiPublicPlaidWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/bonuses'
    | '/cards'
    | '/cheat-sheet'
    | '/decide'
    | '/demo'
    | '/home'
    | '/login'
    | '/offers'
    | '/onboarding'
    | '/pay'
    | '/plan'
    | '/privacy'
    | '/purchases'
    | '/settings'
    | '/terms'
    | '/api/public/plaid/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/bonuses'
    | '/cards'
    | '/cheat-sheet'
    | '/decide'
    | '/demo'
    | '/home'
    | '/login'
    | '/offers'
    | '/onboarding'
    | '/pay'
    | '/plan'
    | '/privacy'
    | '/purchases'
    | '/settings'
    | '/terms'
    | '/api/public/plaid/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/bonuses'
    | '/cards'
    | '/cheat-sheet'
    | '/decide'
    | '/demo'
    | '/home'
    | '/login'
    | '/offers'
    | '/onboarding'
    | '/pay'
    | '/plan'
    | '/privacy'
    | '/purchases'
    | '/settings'
    | '/terms'
    | '/api/public/plaid/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  BonusesRoute: typeof BonusesRoute
  CardsRoute: typeof CardsRoute
  CheatSheetRoute: typeof CheatSheetRoute
  DecideRoute: typeof DecideRoute
  DemoRoute: typeof DemoRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  OnboardingRoute: typeof OnboardingRoute
  PayRoute: typeof PayRoute
  PlanRoute: typeof PlanRoute
  PrivacyRoute: typeof PrivacyRoute
  PurchasesRoute: typeof PurchasesRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ApiPublicPlaidWebhookRoute: typeof ApiPublicPlaidWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide': {
      id: '/decide'
      path: '/decide'
      fullPath: '/decide'
      preLoaderRoute: typeof DecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheat-sheet': {
      id: '/cheat-sheet'
      path: '/cheat-sheet'
      fullPath: '/cheat-sheet'
      preLoaderRoute: typeof CheatSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonuses': {
      id: '/bonuses'
      path: '/bonuses'
      fullPath: '/bonuses'
      preLoaderRoute: typeof BonusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plaid/webhook': {
      id: '/api/public/plaid/webhook'
      path: '/api/public/plaid/webhook'
      fullPath: '/api/public/plaid/webhook'
      preLoaderRoute: typeof ApiPublicPlaidWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  BonusesRoute: BonusesRoute,
  CardsRoute: CardsRoute,
  CheatSheetRoute: CheatSheetRoute,
  DecideRoute: DecideRoute,
  DemoRoute: DemoRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  OnboardingRoute: OnboardingRoute,
  PayRoute: PayRoute,
  PlanRoute: PlanRoute,
  PrivacyRoute: PrivacyRoute,
  PurchasesRoute: PurchasesRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ApiPublicPlaidWebhookRoute: ApiPublicPlaidWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
