
INSERT INTO public.points_programs (id, name, kind, default_cpp) VALUES
  ('chase_ur',    'Chase Ultimate Rewards', 'transferable', 0.0175),
  ('amex_mr',     'Amex Membership Rewards','transferable', 0.017),
  ('capone_miles','Capital One Miles',      'transferable', 0.0145),
  ('citi_typ',    'Citi ThankYou',          'transferable', 0.016),
  ('bilt_pts',    'Bilt Rewards',           'transferable', 0.018),
  ('cashback',    'Cashback',               'cashback',     0.01),
  ('discover_cb', 'Discover Cashback',      'cashback',     0.01),
  ('usb_altitude','US Bank Altitude',       'transferable', 0.015)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.merchants_catalog (id, name, category, aliases) VALUES
  ('whole_foods',    'Whole Foods',           'groceries',      ARRAY['wholefoods','wfm']),
  ('trader_joes',    'Trader Joe''s',         'groceries',      ARRAY['tjs']),
  ('costco',         'Costco',                'wholesale_club', ARRAY[]::text[]),
  ('target',         'Target',                'department',     ARRAY[]::text[]),
  ('walmart',        'Walmart',               'department',     ARRAY[]::text[]),
  ('amazon',         'Amazon',                'online_shopping',ARRAY['amzn']),
  ('starbucks',      'Starbucks',             'dining',         ARRAY['sbux']),
  ('chipotle',       'Chipotle',              'dining',         ARRAY[]::text[]),
  ('uber',           'Uber',                  'transit',        ARRAY['uber eats']),
  ('lyft',           'Lyft',                  'transit',        ARRAY[]::text[]),
  ('united',         'United Airlines',       'airline',        ARRAY['ua']),
  ('delta',          'Delta Air Lines',       'airline',        ARRAY[]::text[]),
  ('american_air',   'American Airlines',     'airline',        ARRAY['aa']),
  ('southwest',      'Southwest Airlines',    'airline',        ARRAY['wn']),
  ('hyatt',          'Hyatt',                 'hotel',          ARRAY[]::text[]),
  ('marriott',       'Marriott',              'hotel',          ARRAY[]::text[]),
  ('hilton',         'Hilton',                'hotel',          ARRAY[]::text[]),
  ('shell',          'Shell',                 'gas',            ARRAY[]::text[]),
  ('exxon',          'Exxon',                 'gas',            ARRAY['exxonmobil']),
  ('apple',          'Apple',                 'online_shopping',ARRAY['app store']),
  ('netflix',        'Netflix',               'streaming',      ARRAY[]::text[]),
  ('doordash',       'DoorDash',              'dining',         ARRAY['dashpass'])
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.cards_catalog (id, is_custom, user_id, issuer, name, annual_fee, foreign_tx_fee_pct, points_program_id, earn_rules, notes) VALUES
  ('csp',       false, NULL, 'Chase',        'Sapphire Preferred',   95,  0,     'chase_ur',
    '[{"category":"dining","multiplier":3},{"category":"streaming","multiplier":3},{"category":"online_shopping","multiplier":3},{"category":"hotel","multiplier":2},{"category":"airline","multiplier":2},{"category":"transit","multiplier":2},{"category":"all","multiplier":1}]'::jsonb, NULL),
  ('csr',       false, NULL, 'Chase',        'Sapphire Reserve',    550,  0,     'chase_ur',
    '[{"category":"dining","multiplier":3},{"category":"hotel","multiplier":3},{"category":"airline","multiplier":3},{"category":"transit","multiplier":3},{"category":"all","multiplier":1}]'::jsonb, NULL),
  ('cfu',       false, NULL, 'Chase',        'Freedom Unlimited',     0,  0.03,  'chase_ur',
    '[{"category":"dining","multiplier":3},{"category":"drugstore","multiplier":3},{"category":"all","multiplier":1.5}]'::jsonb, NULL),
  ('cff',       false, NULL, 'Chase',        'Freedom Flex',          0,  0.03,  'chase_ur',
    '[{"category":"dining","multiplier":3},{"category":"drugstore","multiplier":3},{"category":"rotating","multiplier":5},{"category":"all","multiplier":1}]'::jsonb, 'Rotating 5% categories, $1,500 cap per quarter'),
  ('gold',      false, NULL, 'American Express','Gold',              325,  0,     'amex_mr',
    '[{"category":"dining","multiplier":4},{"category":"groceries","multiplier":4},{"category":"airline","multiplier":3},{"category":"all","multiplier":1}]'::jsonb, NULL),
  ('platinum',  false, NULL, 'American Express','Platinum',          695,  0,     'amex_mr',
    '[{"category":"airline","multiplier":5},{"category":"hotel","multiplier":5},{"category":"all","multiplier":1}]'::jsonb, NULL),
  ('green',     false, NULL, 'American Express','Green',             150,  0,     'amex_mr',
    '[{"category":"dining","multiplier":3},{"category":"transit","multiplier":3},{"category":"airline","multiplier":3},{"category":"hotel","multiplier":3},{"category":"all","multiplier":1}]'::jsonb, NULL),
  ('bcp',       false, NULL, 'American Express','Blue Cash Preferred', 95, 0.027, 'cashback',
    '[{"category":"groceries","multiplier":0.06},{"category":"streaming","multiplier":0.06},{"category":"gas","multiplier":0.03},{"category":"transit","multiplier":0.03},{"category":"all","multiplier":0.01}]'::jsonb, NULL),
  ('bce',       false, NULL, 'American Express','Blue Cash Everyday',  0, 0.027, 'cashback',
    '[{"category":"groceries","multiplier":0.03},{"category":"gas","multiplier":0.03},{"category":"online_shopping","multiplier":0.03},{"category":"all","multiplier":0.01}]'::jsonb, NULL),
  ('citi_dc',   false, NULL, 'Citi',         'Double Cash',           0,  0.03,  'cashback',
    '[{"category":"all","multiplier":0.02}]'::jsonb, NULL),
  ('citi_prem', false, NULL, 'Citi',         'Premier',              95,  0.03,  'citi_typ',
    '[{"category":"dining","multiplier":3},{"category":"groceries","multiplier":3},{"category":"gas","multiplier":3},{"category":"airline","multiplier":3},{"category":"hotel","multiplier":3},{"category":"all","multiplier":1}]'::jsonb, NULL),
  ('citi_cc',   false, NULL, 'Citi',         'Custom Cash',           0,  0.03,  'cashback',
    '[{"category":"top_category","multiplier":0.05},{"category":"all","multiplier":0.01}]'::jsonb, '5% on top eligible category, $500/mo cap'),
  ('vx',        false, NULL, 'Capital One',  'Venture X',           395,  0,     'capone_miles',
    '[{"category":"hotel","multiplier":10},{"category":"rental_car","multiplier":10},{"category":"airline","multiplier":5},{"category":"all","multiplier":2}]'::jsonb, NULL),
  ('venture',   false, NULL, 'Capital One',  'Venture',              95,  0,     'capone_miles',
    '[{"category":"hotel","multiplier":5},{"category":"rental_car","multiplier":5},{"category":"all","multiplier":2}]'::jsonb, NULL),
  ('savorone',  false, NULL, 'Capital One',  'SavorOne',              0,  0,     'cashback',
    '[{"category":"dining","multiplier":0.03},{"category":"streaming","multiplier":0.03},{"category":"groceries","multiplier":0.03},{"category":"all","multiplier":0.01}]'::jsonb, NULL),
  ('discover_it', false, NULL, 'Discover',   'it Cash Back',          0,  0,     'discover_cb',
    '[{"category":"rotating","multiplier":0.05},{"category":"all","multiplier":0.01}]'::jsonb, 'Rotating 5%, $1,500 cap per quarter'),
  ('wf_active', false, NULL, 'Wells Fargo',  'Active Cash',           0,  0.03,  'cashback',
    '[{"category":"all","multiplier":0.02}]'::jsonb, NULL),
  ('usb_go',    false, NULL, 'US Bank',      'Altitude Go',           0,  0,     'usb_altitude',
    '[{"category":"dining","multiplier":4},{"category":"streaming","multiplier":2},{"category":"groceries","multiplier":2},{"category":"gas","multiplier":2},{"category":"all","multiplier":1}]'::jsonb, NULL),
  ('usb_connect', false, NULL, 'US Bank',    'Altitude Connect',     95,  0,     'usb_altitude',
    '[{"category":"airline","multiplier":5},{"category":"hotel","multiplier":5},{"category":"rental_car","multiplier":5},{"category":"dining","multiplier":4},{"category":"gas","multiplier":4},{"category":"streaming","multiplier":4},{"category":"all","multiplier":1}]'::jsonb, NULL),
  ('bilt',      false, NULL, 'Wells Fargo',  'Bilt',                  0,  0,     'bilt_pts',
    '[{"category":"rent","multiplier":1},{"category":"dining","multiplier":3},{"category":"transit","multiplier":2},{"category":"airline","multiplier":2},{"category":"all","multiplier":1}]'::jsonb, 'Rent 1x with no fee')
ON CONFLICT (id) DO NOTHING;
