
-- Update points program default cents-per-point valuations (dollars-per-point).
UPDATE public.points_programs SET default_cpp = 0.0205 WHERE id = 'chase_ur';
UPDATE public.points_programs SET default_cpp = 0.02   WHERE id = 'amex_mr';
UPDATE public.points_programs SET default_cpp = 0.0185 WHERE id = 'capone_miles';
UPDATE public.points_programs SET default_cpp = 0.019  WHERE id = 'citi_typ';
UPDATE public.points_programs SET default_cpp = 0.016  WHERE id = 'hyatt_wob';
UPDATE public.points_programs SET default_cpp = 0.013  WHERE id = 'united_ma';
UPDATE public.points_programs SET default_cpp = 0.012  WHERE id = 'delta_sky';
UPDATE public.points_programs SET default_cpp = 0.022  WHERE id = 'bilt';
UPDATE public.points_programs SET default_cpp = 0.01   WHERE id = 'cashback';

-- Wipe existing non-custom seed rows so we can reseed from a single source of truth.
-- Custom user-authored cards (is_custom=true / user_id set) are preserved.
DELETE FROM public.cards_catalog WHERE is_custom = false;

-- Reinsert the canonical top-25 catalog.
INSERT INTO public.cards_catalog (id, issuer, name, annual_fee, points_program_id, foreign_tx_fee_pct, earn_rules, rates_as_of, notes) VALUES
('chase_csp', 'Chase', 'Sapphire Preferred', 95, 'chase_ur', 0, '[{"category":"travel_portal","multiplier":5},{"category":"dining","multiplier":3},{"category":"online_groceries","multiplier":3},{"category":"streaming","multiplier":3},{"category":"travel","multiplier":2},{"category":"everything_else","multiplier":1}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against chase.com'),
('chase_csr', 'Chase', 'Sapphire Reserve', 795, 'chase_ur', 0, '[{"category":"travel_portal","multiplier":8},{"category":"flights","multiplier":4},{"category":"hotels","multiplier":4},{"category":"dining","multiplier":3},{"category":"everything_else","multiplier":1}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against chase.com'),
('chase_freedom_unlimited', 'Chase', 'Freedom Unlimited', 0, 'chase_ur', 3, '[{"category":"travel_portal","multiplier":5},{"category":"dining","multiplier":3},{"category":"drugstores","multiplier":3},{"category":"everything_else","multiplier":1.5}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against chase.com'),
('chase_freedom_flex', 'Chase', 'Freedom Flex', 0, 'chase_ur', 3, '[{"category":"rotating_5pct","multiplier":0.05,"cap_period_spend":1500,"cap_period":"quarterly"},{"category":"travel_portal","multiplier":5},{"category":"dining","multiplier":3},{"category":"drugstores","multiplier":3},{"category":"everything_else","multiplier":1}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against chase.com'),
('chase_world_of_hyatt', 'Chase', 'World of Hyatt', 95, 'hyatt_wob', 0, '[{"category":"hotels","multiplier":4},{"category":"dining","multiplier":2},{"category":"flights","multiplier":2},{"category":"transit","multiplier":2},{"category":"everything_else","multiplier":1}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against chase.com'),
('chase_united_explorer', 'Chase', 'United Explorer', 150, 'united_ma', 0, '[{"category":"flights","multiplier":3},{"category":"dining","multiplier":2},{"category":"hotels","multiplier":2},{"category":"everything_else","multiplier":1}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against chase.com'),
('chase_amazon_prime_visa', 'Chase', 'Amazon Prime Visa', 0, 'cashback', 3, '[{"category":"amazon","multiplier":0.05},{"category":"whole_foods","multiplier":0.05},{"category":"travel_portal","multiplier":0.05},{"category":"gas","multiplier":0.02},{"category":"dining","multiplier":0.02},{"category":"transit","multiplier":0.02},{"category":"everything_else","multiplier":0.01}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against chase.com'),
('amex_platinum', 'American Express', 'Platinum', 895, 'amex_mr', 0, '[{"category":"flights","multiplier":5,"cap_period_spend":500000,"cap_period":"annual"},{"category":"hotels","multiplier":5},{"category":"everything_else","multiplier":1}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against americanexpress.com'),
('amex_gold', 'American Express', 'Gold', 325, 'amex_mr', 0, '[{"category":"dining","multiplier":4,"cap_period_spend":50000,"cap_period":"annual"},{"category":"groceries","multiplier":4,"cap_period_spend":25000,"cap_period":"annual"},{"category":"hotels","multiplier":5},{"category":"flights","multiplier":3},{"category":"everything_else","multiplier":1}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against americanexpress.com'),
('amex_blue_cash_preferred', 'American Express', 'Blue Cash Preferred', 95, 'cashback', 2.7, '[{"category":"groceries","multiplier":0.06,"cap_period_spend":6000,"cap_period":"annual"},{"category":"streaming","multiplier":0.06},{"category":"transit","multiplier":0.03},{"category":"gas","multiplier":0.03},{"category":"everything_else","multiplier":0.01}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against americanexpress.com'),
('amex_blue_cash_everyday', 'American Express', 'Blue Cash Everyday', 0, 'cashback', 2.7, '[{"category":"groceries","multiplier":0.03,"cap_period_spend":6000,"cap_period":"annual"},{"category":"amazon","multiplier":0.03,"cap_period_spend":6000,"cap_period":"annual"},{"category":"gas","multiplier":0.03,"cap_period_spend":6000,"cap_period":"annual"},{"category":"everything_else","multiplier":0.01}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against americanexpress.com'),
('amex_delta_gold', 'American Express', 'Delta SkyMiles Gold', 150, 'delta_sky', 0, '[{"category":"dining","multiplier":2},{"category":"groceries","multiplier":2},{"category":"flights","multiplier":2},{"category":"everything_else","multiplier":1}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against americanexpress.com'),
('citi_double_cash', 'Citi', 'Double Cash', 0, 'citi_typ', 3, '[{"category":"travel_portal","multiplier":0.05},{"category":"everything_else","multiplier":0.02}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against citi.com'),
('citi_custom_cash', 'Citi', 'Custom Cash', 0, 'citi_typ', 3, '[{"category":"top_category","multiplier":0.05,"cap_period_spend":500,"cap_period":"monthly"},{"category":"everything_else","multiplier":0.01}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against citi.com'),
('citi_strata_premier', 'Citi', 'Strata Premier', 95, 'citi_typ', 0, '[{"category":"hotels","multiplier":10},{"category":"flights","multiplier":3},{"category":"dining","multiplier":3},{"category":"gas","multiplier":3},{"category":"groceries","multiplier":3},{"category":"everything_else","multiplier":1}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against citi.com'),
('capone_venture_x', 'Capital One', 'Venture X', 395, 'capone_miles', 0, '[{"category":"hotels","multiplier":10},{"category":"flights","multiplier":5},{"category":"everything_else","multiplier":2}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against capitalone.com'),
('capone_venture', 'Capital One', 'Venture', 95, 'capone_miles', 0, '[{"category":"hotels","multiplier":5},{"category":"everything_else","multiplier":2}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against capitalone.com'),
('capone_savor', 'Capital One', 'Savor', 0, 'cashback', 0, '[{"category":"hotels","multiplier":0.05},{"category":"groceries","multiplier":0.03},{"category":"dining","multiplier":0.03},{"category":"entertainment","multiplier":0.03},{"category":"streaming","multiplier":0.03},{"category":"everything_else","multiplier":0.01}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against capitalone.com'),
('discover_it_cash_back', 'Discover', 'it Cash Back', 0, 'cashback', 0, '[{"category":"rotating_5pct","multiplier":0.05,"cap_period_spend":1500,"cap_period":"quarterly"},{"category":"everything_else","multiplier":0.01}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against discover.com'),
('boa_customized_cash', 'Bank of America', 'Customized Cash Rewards', 0, 'cashback', 3, '[{"category":"choose_category","multiplier":0.03,"cap_period_spend":2500,"cap_period":"quarterly"},{"category":"groceries","multiplier":0.02},{"category":"wholesale_clubs","multiplier":0.02},{"category":"everything_else","multiplier":0.01}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against bankofamerica.com'),
('boa_premium_rewards', 'Bank of America', 'Premium Rewards', 95, 'cashback', 0, '[{"category":"travel","multiplier":0.02},{"category":"dining","multiplier":0.02},{"category":"everything_else","multiplier":0.015}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against bankofamerica.com'),
('wf_active_cash', 'Wells Fargo', 'Active Cash', 0, 'cashback', 3, '[{"category":"everything_else","multiplier":0.02}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against wellsfargo.com'),
('wf_autograph', 'Wells Fargo', 'Autograph', 0, 'cashback', 3, '[{"category":"dining","multiplier":3},{"category":"travel","multiplier":3},{"category":"gas","multiplier":3},{"category":"transit","multiplier":3},{"category":"streaming","multiplier":3},{"category":"everything_else","multiplier":1}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against wellsfargo.com'),
('usbank_altitude_go', 'US Bank', 'Altitude Go', 0, 'cashback', 3, '[{"category":"dining","multiplier":0.04,"cap_period_spend":2000,"cap_period":"quarterly"},{"category":"groceries","multiplier":0.02},{"category":"gas","multiplier":0.02},{"category":"streaming","multiplier":0.02},{"category":"everything_else","multiplier":0.01}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against usbank.com'),
('bilt_mastercard', 'Bilt', 'Mastercard', 0, 'bilt', 0, '[{"category":"dining","multiplier":3},{"category":"hotels","multiplier":3},{"category":"flights","multiplier":2},{"category":"rent","multiplier":1},{"category":"everything_else","multiplier":1}]'::jsonb, '2026-07-12', 'Verified 2026-07-12 against bilt.com');
